name: TheCorkster
favicon: null
layout_spectrum: 0.48844
typography_spectrum: 0.31756
title: TheCorkster - Minecraft tips and tricks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070930'
    - '#959595'
    - '#5e5e5e'
    - '#fefefe'
    - '#5e2f18'
  brandStrength: 0.664102089125663
  lightness: 0.125
  saturation: 0.05076175695285201
  rhythmicContrast: 0.6432608994655311
purpose: []
